# Generated by Django 3.0.4 on 2020-03-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
