# Generated by Django 3.0.4 on 2020-03-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200318_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='correct',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
